// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkfawlKAlYkzcX1gzltPTdjp98xrINQxA',
    appId: '1:939161789598:web:30a0b3162582fdf5bcc78f',
    messagingSenderId: '939161789598',
    projectId: 'furniture-shopping-app-55979',
    authDomain: 'furniture-shopping-app-55979.firebaseapp.com',
    storageBucket: 'furniture-shopping-app-55979.appspot.com',
    measurementId: 'G-HQF2H28GD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBnnFaC6zg2N7kAgpJizjiyzqEDxU_vKw',
    appId: '1:939161789598:android:8b15935decc2e794bcc78f',
    messagingSenderId: '939161789598',
    projectId: 'furniture-shopping-app-55979',
    storageBucket: 'furniture-shopping-app-55979.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCazmjkSKG0V1OGtsrg5EPGWAEx-6TLOtY',
    appId: '1:939161789598:ios:e91a387abe5188f9bcc78f',
    messagingSenderId: '939161789598',
    projectId: 'furniture-shopping-app-55979',
    storageBucket: 'furniture-shopping-app-55979.appspot.com',
    iosClientId: '939161789598-5k87vr82pukjd05o837abse6mbl33bdv.apps.googleusercontent.com',
    iosBundleId: 'com.app.furnitureShoppingApp',
  );
}
